name: Run Tests
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        id: run-tests
        run: |
          git clone https://oauth2:$TOKEN_GITHUB@github.com/kalisio/development.git "development"
          source development/workspaces/libs/libs.sh feathers-webpush
          yarn test
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: 8e87a996279373f05f01ce8166aac1bc9dda990e9a2f936af25e5aa11326b127
      - name: Notify on slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_LIBS }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          SLACK_COLOR: ${{ steps.run-tests.outcome == 'success' && 'good' || 'danger' }}
          SLACK_MESSAGE: Test of ${{ github.repository }}@${{ github.ref_name }} by ${{ github.actor }} ${{ steps.run-tests.outcome == 'success' && 'passed' || 'failed' }}
          SLACK_FOOTER: